module.exports = {
  "plugins": [
    "stylelint-scss"
  ],
  "rules": {
    // What seems to be the most important rules:
    "indentation": 4,
    "string-quotes": "double",
    "selector-max-compound-selectors": 2,
    "no-descending-specificity": true,
    "declaration-no-important": true,
    "stylelint-disable-reason": "always-after",
    "no-unsupported-browser-features": [true, {
      "severity": "warning"
    }],
    // "selector-max-specificity": "0,0,2", // have to look up what we want here

    // "selector-no-attribute": true,
    // "selector-no-combinator": true,
    "selector-no-id": true,
    "selector-no-qualifying-type": true,
    // "selector-no-type": false,
    "selector-type-no-unknown": true,
    // We will probably want to do something with this
    // "declaration-block-properties-order": "alphabetical"|[],


    // scss rules
    "scss/selector-no-redundant-nesting-selector": true,
    "scss/at-extend-no-missing-placeholder": true,
    "scss/at-import-no-partial-leading-underscore": true,

    // all other rules listed alphabetically
    "at-rule-empty-line-before": [ "always", {
      except: [ "blockless-group", "first-nested" ],
      ignore: ["after-comment"],
    } ],

    "at-rule-name-case": "lower",
    "at-rule-name-space-after": "always-single-line",
    "at-rule-no-vendor-prefix": true,
    "at-rule-semicolon-newline-after": "always",

    "block-closing-brace-newline-after": "always",
    "block-closing-brace-newline-before": "always-multi-line",
    // "block-closing-brace-space-after": "always-single-line",
    "block-closing-brace-space-before": "always-single-line",
    "block-no-empty": true,
    "block-no-single-line": true,
    "block-opening-brace-newline-after": "always-multi-line",
    "block-opening-brace-space-after": "always-single-line",
    "block-opening-brace-space-before": "always",

    "color-hex-case": "lower",
    "color-hex-length": "long",
    "color-named": "never",
    // "color-no-hex": true,
    "color-no-invalid-hex": true,

    "comment-empty-line-before": [ "always", {
       except: ["first-nested"],
       ignore: ["stylelint-commands"],
     } ],
    "comment-whitespace-inside": "always",
    // "comment-word-blacklist": string|[],

    // "custom-media-pattern": string,
    "custom-property-no-outside-root": true,
    // "custom-property-pattern": string,

    "declaration-bang-space-after": "never",
    "declaration-bang-space-before": "always",
    "declaration-block-no-duplicate-properties": true,
    "declaration-block-no-ignored-properties": true,
    "declaration-block-no-shorthand-property-overrides": true,

    "declaration-block-semicolon-newline-after": "always-multi-line",
    "declaration-block-semicolon-space-after": "always-single-line",
    "declaration-block-semicolon-space-before": "never",
    "declaration-block-single-line-max-declarations": 1,
    "declaration-block-trailing-semicolon": "always",
    // "declaration-colon-newline-after": "always"|"always-multi-line",
    "declaration-colon-space-after": "always",
    "declaration-colon-space-before": "never",

    "font-family-name-quotes": "always-where-recommended",

    "font-weight-notation": "numeric",

    // "function-blacklist": string|[],
    "function-calc-no-unspaced-operator": true,
    "function-comma-newline-after": "never-multi-line",
    "function-comma-newline-before": "never-multi-line",
    "function-comma-space-after": "always",
    "function-comma-space-before": "never",
    "function-linear-gradient-no-nonstandard-direction": true,
    "function-max-empty-lines": 2,
    "function-name-case": "lower",
    "function-parentheses-newline-inside": "never-multi-line",
    "function-parentheses-space-inside": "always",
    // "function-url-data-uris": "always"|"never",
    "function-url-quotes": "always",
    // "function-whitelist": string|[],
    "function-whitespace-after": "never",

    // "keyframe-declaration-no-important": false,

    "max-empty-lines": 1,
    "max-line-length": 300,

    "max-nesting-depth": 3,

    "media-feature-colon-space-after": "always",
    "media-feature-colon-space-before": "never",
    "media-feature-name-no-vendor-prefix": true,
    "media-feature-no-missing-punctuation": true,
    "media-feature-range-operator-space-after": "always",
    "media-feature-range-operator-space-before": "never",
    "media-query-list-comma-newline-after": "always-multi-line",
    "media-query-list-comma-newline-before": "never-multi-line",
    "media-query-list-comma-space-after": "always",
    "media-query-list-comma-space-before": "never",
    "media-query-parentheses-space-inside": "always",
    "no-browser-hacks": true,
    "no-duplicate-selectors": true,
    "no-eol-whitespace": true,
    "no-extra-semicolons": true,
    "no-indistinguishable-colors": true,
    "no-invalid-double-slash-comments": true,
    "no-missing-eof-newline": true,
    "no-unknown-animations": true,
    "number-leading-zero": "always",
    "number-max-precision": 3,
    "number-no-trailing-zeros": true,
    "number-zero-length-no-unit": true,
    // "property-blacklist": string|[],
    "property-case": "lower",
    "property-no-vendor-prefix": true,
    // "property-unit-blacklist": {},
    // "property-unit-whitelist": {},
    // "property-value-blacklist": {},
    // "property-value-whitelist": {},
    // "property-whitelist": string|[],
    "root-no-standard-properties": true,
    "rule-nested-empty-line-before": "always",
    "rule-non-nested-empty-line-before": "always",
    "selector-attribute-brackets-space-inside": "always",
    // "selector-attribute-operator-blacklist": string|[],
    "selector-attribute-operator-space-after": "never",
    "selector-attribute-operator-space-before": "never",
    // "selector-attribute-operator-whitelist": string|[],
    // "selector-class-pattern": string,
    "selector-combinator-space-after": "always",
    "selector-combinator-space-before": "never",
    // "selector-id-pattern": string,
    "selector-list-comma-newline-after": "always-multi-line",
    "selector-list-comma-newline-before": "never-multi-line",
    "selector-list-comma-space-after": "always-single-line",
    "selector-list-comma-space-before": "never",
    "selector-max-empty-lines": 1,
    "selector-no-universal": true,
    "selector-no-vendor-prefix": true,
    "selector-pseudo-class-case": "lower",
    "selector-pseudo-class-no-unknown": true,
    "selector-pseudo-class-parentheses-space-inside": "always",
    "selector-pseudo-element-case": "lower",
    "selector-pseudo-element-colon-notation": "double",
    "selector-pseudo-element-no-unknown": true,
    "selector-root-no-composition": true,
    "selector-type-case": "lower",

    "shorthand-property-no-redundant-values": true,
    "string-no-newline": true,
    "time-no-imperceptible": true,
    // "unit-blacklist": string|[],
    "unit-case": "lower",
    "unit-no-unknown": true,
    // "unit-whitelist": string|[],
    "value-keyword-case": "lower",
    "value-list-comma-newline-after": "never-multi-line",
    "value-list-comma-newline-before": "never-multi-line",
    "value-list-comma-space-after": "always",
    "value-list-comma-space-before": "never",
    "value-no-vendor-prefix": true
  }
}
